# Generated by Django 2.1 on 2018-08-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='given',
            field=models.BooleanField(default=False),
        ),
    ]
