# Generated by Django 2.1 on 2018-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transaction_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(0, 'Ожидает выдачи'), (1, 'Завершена'), (2, 'Отменена')], default=0, verbose_name='Состояние транзакции'),
        ),
    ]
