# Generated by Django 2.1 on 2018-08-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transaction_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='given',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reverted',
        ),
    ]
