# Generated by Django 2.1 on 2018-08-22 19:28

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость товара')),
                ('amount', models.IntegerField(verbose_name='Кол-во на складе')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to=shop.models.get_image_path, verbose_name='Картинка')),
                ('single_buy', models.BooleanField(default=False, verbose_name='Один товар на человека')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
