# Generated by Django 2.1 on 2018-08-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_hidden_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='only_online',
            field=models.BooleanField(default=False, help_text='Автоматически помечает транзакцию выполненной!', verbose_name='Не требует offline выдачи'),
        ),
    ]
