# Generated by Django 2.1 on 2018-08-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleuser',
            name='squad',
        ),
    ]
